# Ejemplo de configuración de secrets para Streamlit Cloud
# Copia esta configuración en la sección "Secrets" de tu app en Streamlit Cloud

[google]
# Configuración de claves API de Google Gemini en formato array
api_keys = [
    {key = "TU_CLAVE_API_1", name = "clave_1"},
    {key = "TU_CLAVE_API_2", name = "clave_2"},
    {key = "TU_CLAVE_API_3", name = "clave_3"}
]

# Para obtener claves API de Google Gemini:
# 1. Ve a https://makersuite.google.com/app/apikey
# 2. Crea un nuevo API key
# 3. Reemplaza "TU_CLAVE_API_X" con tu clave real
# 4. Repite para crear múltiples claves para mayor estabilidad
