# Ejemplo de configuración de secrets para Streamlit Cloud
# Copia este archivo como secrets.toml y configura tus claves reales

[gemini]
# Añade aquí tus claves API de Google Gemini
# Puedes añadir múltiples claves para rotación automática
api_key_1 = "AIza..."
api_key_2 = "AIza..."
api_key_3 = "AIza..."

# Para obtener claves API de Google Gemini:
# 1. Ve a https://makersuite.google.com/app/apikey
# 2. Crea un nuevo API key
# 3. Copia la clave y pégala arriba
# 4. Repite para crear múltiples claves si quieres mayor estabilidad
